// src/react/views/Home.js
import React from 'react';

import { HelloWorldClass } from '@/react/components/HelloWorld';

export default function Home() {
  return (
    <div className="home">
      <img alt="Vue logo" src="/static/react-logo.png" width="200" />
      <HelloWorldClass msg="Welcome to Your React App" />
    </div>
  );
}

// src/vue/views/Home.vue
<template lang="pug">
.home
  img(alt="Vue logo" src="/static/logo.png" width="200")
  hello-world(msg="Welcome to Your Vue.js App")
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/vue/components/HelloWorld.vue';

export default {
  name: 'Home',
  components: {
    HelloWorld,
  },
};
</script>
